# Generated by Django 5.0.6 on 2024-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("named_entity_recognition", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="name",
        ),
        migrations.AlterField(
            model_name="document",
            name="upload",
            field=models.FileField(upload_to="named_entity_recognition/uploads"),
        ),
    ]
